### PR TITLE
sanity

### PR DESCRIPTION
**Pull request by austinmargarone**
Did I set this up properly?

### CODE REVIEW

**Comment by austinmargarone** [comment]
I noticed that my .env got pushed into here even though it's within my .gitignore.

**Comment by Nassim-Saboundji** [comment]
Did you make this PR after the office hours we had yesterday? Did you follow the article that we shared with you. I'm just wondering if this PR is up to date before reviewing.

**Comment by austinmargarone** [comment]
@Nassim-Saboundji  No. I had made this before we spoke in office hours, I'll cancel this one.

**Comment by austinmargarone** [comment]
@Nassim-Saboundji  Going to make a new branch.

**Pull request closed without merging**
